import {
  riEyeLine,
  riCheckLine,
  riCloseLine,
  riCursorLine,
  riEyeOffLine,
  riFileCopyLine,
  riDragMoveLine,
  riSettings3Line,
  riListUnordered,
  riArrowLeftLine,
  riArrowLeftSLine,
  riInformationLine,
  riArrowDropDownLine,
} from 'v-remixicon/icons';

export default {
  riEyeLine,
  riCheckLine,
  riCloseLine,
  riCursorLine,
  riEyeOffLine,
  riFileCopyLine,
  riDragMoveLine,
  riSettings3Line,
  riListUnordered,
  riArrowLeftLine,
  riArrowLeftSLine,
  riInformationLine,
  riArrowDropDownLine,
};
